const express = require('express');
const crypto = require('node:crypto');
const multer = require('multer');
const db = require('../db');
const storage = require('../lib/storage');
const ai = require('../lib/ai');
const { requireAuth, requireRole } = require('../middleware/auth');

const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 50 * 1024 * 1024 } });

function serialize(r) {
  return {
    id: r.id,
    title: r.title,
    kind: r.kind,
    note: r.note,
    group: r.group_name || 'Ungrouped',
    createdAt: r.created_at,
    deleted: !!r.deleted_at,
    hasFile: !!r.file_key,
    fileName: r.file_name,
    mimeType: r.mime_type,
    sizeBytes: r.size_bytes,
  };
}

// List active items (or the trash with ?trash=1).
router.get('/', requireAuth, (req, res) => {
  const trash = req.query.trash === '1';
  const rows = db
    .prepare(`SELECT * FROM library_items WHERE academy_id = ? AND deleted_at IS ${trash ? 'NOT NULL' : 'NULL'} ORDER BY created_at DESC`)
    .all(req.user.academy_id);
  res.json({ items: rows.map(serialize) });
});

async function storeFile(req, academyId) {
  const f = req.file;
  const fileName = f.originalname;
  const fileKey = `academy-${academyId}/${Date.now()}-${crypto.randomBytes(4).toString('hex')}-${fileName}`;
  await storage.putObject(fileKey, f.buffer, f.mimetype);
  return { fileKey, fileName, mimeType: f.mimetype, sizeBytes: f.size };
}

// Publish content (optional file, optional group).
router.post('/', requireAuth, requireRole('tutor'), upload.single('file'), async (req, res) => {
  const { title, kind, note, group } = req.body || {};
  if (!title) return res.status(400).json({ error: 'title is required.' });
  let meta = { fileKey: null, fileName: null, mimeType: null, sizeBytes: null };
  if (req.file) {
    try { meta = await storeFile(req, req.user.academy_id); }
    catch (err) { return res.status(502).json({ error: 'File upload failed: ' + err.message }); }
  }
  const info = db.prepare(`INSERT INTO library_items
    (academy_id, created_by, title, kind, note, group_name, file_key, file_name, mime_type, size_bytes)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .run(req.user.academy_id, req.user.id, title, kind || 'Notes', note || null, (group || '').trim() || null,
         meta.fileKey, meta.fileName, meta.mimeType, meta.sizeBytes);
  res.status(201).json({ item: serialize(db.prepare('SELECT * FROM library_items WHERE id = ?').get(info.lastInsertRowid)) });
});

// AI: generate a lesson image and save it to the Library.
router.post('/generate', requireAuth, requireRole('tutor'), async (req, res) => {
  const { prompt, title, group } = req.body || {};
  if (!prompt) return res.status(400).json({ error: 'Describe the image you want.' });
  try {
    const { buffer, mimeType } = await ai.generateImage(prompt);
    const fileName = `ai-${Date.now()}.png`;
    const fileKey = `academy-${req.user.academy_id}/${Date.now()}-${crypto.randomBytes(4).toString('hex')}-${fileName}`;
    await storage.putObject(fileKey, buffer, mimeType);
    const info = db.prepare(`INSERT INTO library_items
      (academy_id, created_by, title, kind, note, group_name, file_key, file_name, mime_type, size_bytes)
      VALUES (?, ?, ?, 'Image', ?, ?, ?, ?, ?, ?)`)
      .run(req.user.academy_id, req.user.id, (title || prompt).slice(0, 120), 'Generated by AI: ' + prompt.slice(0, 200),
           (group || '').trim() || 'AI images', fileKey, fileName, mimeType, buffer.length);
    res.status(201).json({ item: serialize(db.prepare('SELECT * FROM library_items WHERE id = ?').get(info.lastInsertRowid)) });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

router.get('/ai-status', requireAuth, (req, res) => res.json({ configured: ai.isConfigured() }));

function loadItem(req, res, next) {
  const item = db.prepare('SELECT * FROM library_items WHERE id = ?').get(req.params.id);
  if (!item || item.academy_id !== req.user.academy_id) return res.status(404).json({ error: 'Not found.' });
  req.item = item;
  next();
}

// Move to trash (soft delete).
router.post('/:id/trash', requireAuth, requireRole('tutor'), loadItem, (req, res) => {
  db.prepare("UPDATE library_items SET deleted_at = datetime('now') WHERE id = ?").run(req.item.id);
  res.json({ ok: true });
});

// Restore from trash.
router.post('/:id/restore', requireAuth, requireRole('tutor'), loadItem, (req, res) => {
  db.prepare('UPDATE library_items SET deleted_at = NULL WHERE id = ?').run(req.item.id);
  res.json({ ok: true });
});

// Delete permanently.
router.delete('/:id', requireAuth, requireRole('tutor'), loadItem, (req, res) => {
  db.prepare('DELETE FROM library_items WHERE id = ?').run(req.item.id);
  res.json({ ok: true });
});

// Download / view a file.
router.get('/:id/download', requireAuth, loadItem, async (req, res) => {
  if (!req.item.file_key) return res.status(404).json({ error: 'No file attached.' });
  const mime = req.item.mime_type || '';
  const inline = mime.startsWith('image/') || mime.startsWith('video/') || mime.startsWith('audio/');
  try {
    const url = await storage.getDownloadUrl(req.item.file_key, req.item.file_name, inline);
    if (url) return res.redirect(url);
    const lp = storage.localPath(req.item.file_key);
    if (!lp) return res.status(404).json({ error: 'File missing from storage.' });
    if (inline) { res.type(mime || 'application/octet-stream'); return res.sendFile(lp); }
    return res.download(lp, req.item.file_name || 'download');
  } catch (err) { res.status(502).json({ error: 'Download failed: ' + err.message }); }
});

module.exports = router;
